object Libraries {
    private object Versions {
        const val ktx                           = "1.7.0"
        const val jetPack                       = "1.4.0"
        const val googleMaterial                = "1.4.0"
        const val constraintLayout              = "2.1.2"
        const val retrofit                      = "2.9.0"
        const val retrofitRx                    = "1.0.0"
        const val rxandroid                     = "2.1.1"
        const val rxjava                        = "2.2.10"
        const val rxkotlin                      = "2.4.0"
        const val okHttpInterceptor             = "4.7.2"
        const val lifecycle                     = "2.2.0"
        const val fragmentKtx                   = "1.3.0"
        const val lifecycleLivedata             = "2.3.0"
        const val fragmentVersion               = "1.4.0"
        const val koin                          = "2.2.2"
        const val nav                           = "2.3.5"
        const val picasso                       = "2.71828"
        const val paging                        = "3.1.0"

        const val legacySupport = "1.0.0"
        const val kotlinCoroutines = "1.3.7"
        const val okHttp            = "2.7.4"
        const val gson = "2.8.6"
        const val glideVersion = "4.11.0"
        const val room = "2.2.5"
        const val debugDatabase     = "1.0.6"
    }

    const val ktxCore                  = "androidx.core:core-ktx:${Versions.ktx}"
    const val appCompat                = "androidx.appcompat:appcompat:${Versions.jetPack}"
    const val googleMaterial           = "com.google.android.material:material:${Versions.googleMaterial}"
    const val constraintLayout         = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val retrofit                 = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitGson             = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val retrofitRx               = "com.jakewharton.retrofit:retrofit2-rxjava2-adapter:${Versions.retrofitRx}"
    const val rxandroid                = "io.reactivex.rxjava2:rxandroid:${Versions.rxandroid}"
    const val rxjava                   = "io.reactivex.rxjava2:rxjava:${Versions.rxjava}"
    const val rxkotlin                 = "io.reactivex.rxjava2:rxkotlin:${Versions.rxkotlin}"
    const val kotlinStdLib             = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"
    const val okHttpInteceptor         = "com.squareup.okhttp3:logging-interceptor:${Versions.okHttpInterceptor}"
    const val lifeCycleExtensions      = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycle}"
    const val fragmentKtx              = "androidx.fragment:fragment-ktx:${Versions.fragmentKtx}"
    const val fragmentVersion          = "androidx.fragment:fragment-ktx:${Versions.fragmentVersion}"
    const val lifecycleLivedata        = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycleLivedata}"
    const val koinAndroidScopes        = "org.koin:koin-androidx-scope:${Versions.koin}"
    const val koinAndroidViewModel     = "org.koin:koin-androidx-viewmodel:${Versions.koin}"
    const val koinFragment             = "org.koin:koin-androidx-fragment:${Versions.koin}"
    const val koinWorkmanager          = "org.koin:koin-androidx-workmanager:${Versions.koin}"
    const val navFragment              = "androidx.navigation:navigation-fragment-ktx:${Versions.nav}"
    const val navUi                    = "androidx.navigation:navigation-ui-ktx:${Versions.nav}"
    const val picasso                  = "com.squareup.picasso:picasso:${Versions.picasso}"

    const val pagingRuntime            = "androidx.paging:paging-runtime-ktx:${Versions.paging}"
    const val pagingRx                 = "androidx.paging:paging-rxjava2-ktx:${Versions.paging}"




    const val legacySupport            = "androidx.legacy:legacy-support-v4:${Versions.legacySupport}"
    const val lifeCycleViewModel       = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"

    const val lifeCycleCompiler        = "androidx.lifecycle:lifecycle-compiler:${Versions.lifecycle}"
    const val koinCore                 = "org.koin:koin-core:${Versions.koin}"
    const val koinAndroid              = "org.koin:koin-android:${Versions.koin}"

    const val kotlinCoroutinesCore     = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.kotlinCoroutines}"
    const val kotlinCoroutinesAndroid  = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.kotlinCoroutines}"
    const val gson                     = "com.google.code.gson:gson:${Versions.gson}"
    const val okHttp                   = "com.squareup.okhttp:okhttp:${Versions.okHttp}"


    const val glide                    = "com.github.bumptech.glide:glide:${Versions.glideVersion}"
    const val glideCompiler             = "com.github.bumptech.glide:compiler:${Versions.glideVersion}"
    const val roomRuntime              = "androidx.room:room-runtime:${Versions.room}"
    const val roomKtx                  = "androidx.room:room-ktx:${Versions.room}"
    const val roomCompiler             = "androidx.room:room-compiler:${Versions.room}"
    const val debugDatabase            = "com.amitshekhar.android:debug-db:${Versions.debugDatabase}"
}